import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ContentBlocks,contentAsset} from '../src/ContentBlocks';
import './style.css';
const groups=[['columns/zige','子戈的专栏'],['columns/xuyuan','徐元的专栏'],['columns/meixuefeng','梅雪峰的专栏'],['festivals/cannes','戛纳电影节'],['festivals/venice','威尼斯电影节'],['festivals/berlin','柏林电影节']];
const dateNow=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const blankBlock=(type='paragraph')=>({type,text:'',fontSize:type==='h2'?28:type==='h3'?24:20,align:'left',bold:false,italic:false,...(type==='image'?{src:'',alt:'',caption:''}:{}),...(type==='link'?{href:''}:{})});
const id=prefix=>prefix+'-'+crypto.randomUUID().slice(0,8);
function Admin(){
 const [session,setSession]=useState(null),[content,setContent]=useState(null),[revision,setRevision]=useState(''),[tab,setTab]=useState('articles'),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[images,setImages]=useState([]),[picker,setPicker]=useState(null),[preview,setPreview]=useState(false),[query,setQuery]=useState('');
 const username=useRef(null),password=useRef(null),confirmation=useRef(null);
 async function api(route,options={}){const response=await fetch('/api/admin/'+route,{...options,headers:{'Content-Type':'application/json',...(session?.csrf?{'X-CSRF-Token':session.csrf}:{}),...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败。');return data;}
 useEffect(()=>{api('session').then(setSession).catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(session?.authenticated)reload();},[session?.authenticated]);
 useEffect(()=>{const prevent=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 async function reload(){try{const data=await api('content');setContent(data.content);setRevision(data.revision);setDirty(false);setError('');await refreshMedia();}catch(e){setError(e.message);}}
 async function refreshMedia(){const data=await api('media');setImages(data.images);}
 async function authenticate(e){e.preventDefault();setError('');if(session.setup&&password.current.value!==confirmation.current.value){setError('两次密码不一致。');return;}setBusy(true);try{const data=await api(session.setup?'setup':'login',{method:'POST',body:JSON.stringify({username:username.current.value,password:password.current.value})});setSession({authenticated:true,setup:false,csrf:data.csrf});}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function save(){setBusy(true);setError('');setNotice('');try{const data=await api('content',{method:'PUT',body:JSON.stringify({content,revision})});setRevision(data.revision);setDirty(false);setNotice('已保存到本地项目。刷新前台可查看已发布内容；GitHub 尚未更新。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){if(dirty&&!confirm('还有未保存的修改，确定退出？'))return;try{await api('logout',{method:'POST',body:'{}'});setSession({authenticated:false,setup:false});setContent(null);setDirty(false);}catch(e){setError(e.message);}}
 const records=content?.[tab]||[];
 const current=records.find(r=>r.id===selected);
 function mutate(fn){setContent(c=>fn(structuredClone(c)));setDirty(true);setNotice('');}
 function update(values){mutate(c=>{Object.assign(c[tab].find(r=>r.id===selected),values);return c;});}
 function add(){const newId=id(tab==='articles'?'article':'episode');const item=tab==='articles'?{id:newId,title:'未命名文章',subtitle:'',author:'',category:'影评',collection:'columns/zige',status:'draft',publishedAt:dateNow(),cover:'',blocks:[blankBlock()]}:{id:newId,title:'未命名节目',url:'https://www.xiaoyuzhoufm.com/podcast/68c436b4de7cd32c37b1c4a8',cover:'/assets/podcast-cover.png',duration:'',access:'',publishedAt:dateNow()};mutate(c=>{c[tab].unshift(item);return c;});setSelected(newId);setPreview(false);}
 function remove(){if(!confirm('删除「'+current.title+'」？保存后生效。'))return;mutate(c=>{c[tab]=c[tab].filter(r=>r.id!==selected);return c;});setSelected('');}
 function moveRecord(offset){const index=records.findIndex(r=>r.id===selected);if(index+offset<0||index+offset>=records.length)return;mutate(c=>{[c[tab][index],c[tab][index+offset]]=[c[tab][index+offset],c[tab][index]];return c;});}
 function blockUpdate(index,values){const blocks=structuredClone(current.blocks);Object.assign(blocks[index],values);update({blocks});}
 function blockMove(index,offset){const blocks=[...current.blocks];if(index+offset<0||index+offset>=blocks.length)return;[blocks[index],blocks[index+offset]]=[blocks[index+offset],blocks[index]];update({blocks});}
 async function upload(file){if(!file)return;if(file.size>10*1024*1024){setError('图片最大 10 MB。');return;}setBusy(true);setError('');try{const data=await api('upload',{method:'POST',headers:{'Content-Type':file.type},body:file});await refreshMedia();if(picker)chooseImage(data.url);else setNotice('图片已保存到项目图片库。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 function chooseImage(url){if(picker?.type==='cover')update({cover:url});if(picker?.type==='block')blockUpdate(picker.index,{src:url});setPicker(null);}
 if(!session)return <div className="login"><p>{error||'正在连接本地后台…'}</p></div>;
 if(!session.authenticated)return <div className="login"><form onSubmit={authenticate}><span className="eyebrow">PAPERBULLET / LOCAL STUDIO</span><h1>{session.setup?'设置你的后台':'登录内容后台'}</h1><p>文章、图片与播客，在这里整理。</p><label>管理员账号<input ref={username} required minLength={2} maxLength={80} autoComplete="username" autoFocus/></label><label>密码<input ref={password} type="password" required minLength={session.setup?12:1} maxLength={256} autoComplete={session.setup?'new-password':'current-password'}/></label>{session.setup&&<><label>再次输入密码<input ref={confirmation} type="password" required minLength={12} autoComplete="new-password"/></label><small>密码至少 12 个字符。账号仅保存在此电脑。</small></>}<button className="primary" disabled={busy}>{busy?'请稍候…':session.setup?'创建账号并进入':'登录'}</button>{error&&<p className="error" role="alert">{error}</p>}<a href="/" target="_blank" rel="noreferrer">查看网站 ↗</a></form></div>;
 return <div className="studio"><header className="studio-header"><div><span className="eyebrow">PAPERBULLET</span><strong>内容工作室</strong></div><span className={'save-state '+(dirty?'unsaved':'')}>{dirty?'有未保存修改':'已保存'}</span><a href="/" target="_blank" rel="noreferrer">前台预览 ↗</a><button onClick={()=>{if(!dirty||confirm('重新载入会丢弃未保存修改，继续？'))reload();}} disabled={busy}>重新载入</button><button className="primary" disabled={busy||!dirty} onClick={save}>{busy?'处理中…':'保存全部修改'}</button><button onClick={logout} disabled={busy}>退出</button></header>
 <nav className="studio-tabs">{[['articles','文章'],['episodes','播客'],['media','图片库']].map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setSelected('');setPreview(false);setQuery('');}}>{label}<span>{key==='media'?images.length:content?.[key]?.length||0}</span></button>)}</nav>
 <div className="messages" aria-live="polite">{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success">{notice}</p>}</div>
 {!content?<p className="empty">正在载入内容…</p>:tab==='media'?<section className="media-page"><h1>图片库</h1><p>上传后可用作文章封面、正文插图或播客图片。支持 PNG、JPG、WebP、GIF，最大 10 MB。</p><label className="upload-button">上传图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/></label><div className="media-grid">{images.map(img=><div key={img.url}><img src={img.url} alt={img.name}/><small>{img.name}</small><code>{img.url}</code></div>)}</div></section>:<div className="workspace"><aside className="record-list"><div className="list-top"><h2>{tab==='articles'?'文章':'节目'} <small>{records.length}</small></h2><button onClick={add} disabled={busy}>＋ 新建</button></div><input aria-label="搜索内容" placeholder="搜索标题" value={query} onChange={e=>setQuery(e.target.value)}/>{records.filter(r=>r.title.includes(query)).map(r=><button className={'record '+(selected===r.id?'selected':'')} key={r.id} onClick={()=>{setSelected(r.id);setPreview(false);}}><span>{tab==='articles'?(r.status==='published'?'已发布':'草稿'):'播客'}</span><strong>{r.title}</strong><small>{r.publishedAt?.replace('T',' ')||'未设置发布时间'}</small></button>)}{!records.length&&<p className="empty">还没有正式文章。点击新建开始写作；网站中的排版示例会单独保留。</p>}</aside>
 <main className="editor">{!current?<div className="editor-welcome"><span className="eyebrow">YOUR NEXT STORY</span><h1>{tab==='articles'?'从一篇文字开始。':'让声音被听见。'}</h1><p>选择左侧内容继续编辑，或新建一项。</p><button className="primary" onClick={add}>＋ 新建{tab==='articles'?'文章':'节目'}</button></div>:<><div className="editor-top"><span>{tab==='articles'?'文章编辑':'播客编辑'}</span><div><button onClick={()=>moveRecord(-1)} disabled={busy||records[0]===current}>上移</button><button onClick={()=>moveRecord(1)} disabled={busy||records.at(-1)===current}>下移</button>{tab==='articles'&&<button onClick={()=>setPreview(!preview)}>{preview?'继续编辑':'预览排版'}</button>}<button className="danger" onClick={remove} disabled={busy}>删除</button></div></div>
 {preview?<div className="article-preview"><span>{current.author} · {current.publishedAt?.replace('T',' ')}</span><h1>{current.title}</h1><p className="subtitle">{current.subtitle}</p>{current.cover&&<img className="cover-preview" src={contentAsset(current.cover)} alt=""/>}<ContentBlocks blocks={current.blocks}/></div>:<fieldset disabled={busy} className="editor-fields"><label>标题<input className="title-input" value={current.title} onChange={e=>update({title:e.target.value})} maxLength={tab==='articles'?240:400}/></label>
 {tab==='articles'?<><label>导语／摘要<textarea rows={2} value={current.subtitle} onChange={e=>update({subtitle:e.target.value})}/></label><div className="field-row"><label>所属栏目<select value={current.collection} onChange={e=>update({collection:e.target.value})}>{groups.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>状态<select value={current.status} onChange={e=>update({status:e.target.value})}><option value="draft">草稿（前台不可见）</option><option value="published">已发布（保存后前台可见）</option></select></label></div><div className="field-row"><label>作者<input value={current.author} onChange={e=>update({author:e.target.value})}/></label><label>文章分类<input value={current.category} onChange={e=>update({category:e.target.value})}/></label></div></>:<label>跳转链接<input type="url" placeholder="https://www.xiaoyuzhoufm.com/episode/…" value={current.url} onChange={e=>update({url:e.target.value})}/><small>点击节目卡片会打开这个地址。</small></label>}
 <label>发布时间<input type="datetime-local" value={current.publishedAt||''} onInput={e=>update({publishedAt:e.target.value})} onChange={e=>update({publishedAt:e.target.value})}/><small>按填写的日期与时间展示；不自动定时发布，列表顺序用上移／下移调整。</small></label>
 <div className="cover-field"><div><strong>{tab==='articles'?'文章封面（选填）':'播客封面'}</strong><div><button onClick={()=>setPicker({type:'cover'})}>从图片库选择／上传</button>{current.cover&&tab==='articles'&&<button onClick={()=>update({cover:''})}>移除封面</button>}</div></div>{current.cover&&<img src={contentAsset(current.cover)} alt="当前封面"/>}</div>
 {tab==='episodes'?<div className="field-row"><label>时长<input placeholder="如 57分钟" value={current.duration||''} onChange={e=>update({duration:e.target.value})}/></label><label>附加标记<input placeholder="如 试听，可留空" value={current.access||''} onChange={e=>update({access:e.target.value})}/></label></div>:<section className="blocks"><h2>文章正文</h2><p className="hint">逐段编辑文字和图片。每段可独立设置字号、粗体、斜体与对齐，预览排版查看最终效果。</p>{current.blocks.map((b,i)=><div className="block" key={i}><div className="block-toolbar"><span>{String(i+1).padStart(2,'0')}</span><select aria-label={'第'+(i+1)+'段类型'} value={b.type} onChange={e=>blockUpdate(i,{...blankBlock(e.target.value),text:b.text})}>{[['paragraph','正文'],['h2','二级标题'],['h3','三级标题'],['quote','引用'],['image','图片'],['link','链接']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>{b.type!=='image'&&<><select aria-label={'第'+(i+1)+'段字号'} value={b.fontSize} onChange={e=>blockUpdate(i,{fontSize:Number(e.target.value)})}>{[14,16,18,20,22,24,28,32,40,48].map(n=><option key={n} value={n}>{n}px</option>)}</select><button aria-label="粗体" aria-pressed={b.bold} onClick={()=>blockUpdate(i,{bold:!b.bold})}><b>B</b></button><button aria-label="斜体" aria-pressed={b.italic} onClick={()=>blockUpdate(i,{italic:!b.italic})}><i>I</i></button><select aria-label="段落对齐" value={b.align} onChange={e=>blockUpdate(i,{align:e.target.value})}><option value="left">左对齐</option><option value="center">居中</option><option value="right">右对齐</option></select></>}<button aria-label="上移段落" disabled={i===0} onClick={()=>blockMove(i,-1)}>↑</button><button aria-label="下移段落" disabled={i===current.blocks.length-1} onClick={()=>blockMove(i,1)}>↓</button><button aria-label="删除段落" onClick={()=>{if((b.text||b.src)&&!confirm('删除这一段？'))return;update({blocks:current.blocks.filter((_,j)=>j!==i)});}}>×</button></div>{b.type==='image'?<div className="image-block">{b.src&&<img src={contentAsset(b.src)} alt={b.alt}/>}<button onClick={()=>setPicker({type:'block',index:i})}>选择／上传插图</button><label>图片描述<input value={b.alt} onChange={e=>blockUpdate(i,{alt:e.target.value})}/></label><label>图注<input value={b.caption} onChange={e=>blockUpdate(i,{caption:e.target.value})}/></label></div>:<><textarea aria-label={'第'+(i+1)+'段文字'} rows={b.type==='paragraph'?5:2} placeholder="在这里写下文字…" value={b.text} style={{fontSize:b.fontSize,textAlign:b.align,fontWeight:b.bold?700:400,fontStyle:b.italic?'italic':'normal'}} onChange={e=>blockUpdate(i,{text:e.target.value})}/>{b.type==='link'&&<input aria-label="正文链接地址" type="url" value={b.href} onChange={e=>blockUpdate(i,{href:e.target.value})} placeholder="https://…"/>}</>}</div>)}<div className="add-block">{[['paragraph','文字'],['h2','标题'],['quote','引用'],['image','图片'],['link','链接']].map(([type,label])=><button key={type} onClick={()=>update({blocks:[...current.blocks,blankBlock(type)]})}>＋ {label}</button>)}</div></section>}
 <small className="record-id">固定网址标识：{current.id}</small></fieldset>}</> }</main></div>}
 {picker&&<div className="modal-backdrop"><section className="media-modal" role="dialog" aria-modal="true" aria-label="选择图片"><header><h2>选择图片</h2><button onClick={()=>setPicker(null)}>关闭</button></header><label className="upload-button">上传新图片<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" disabled={busy} onChange={e=>upload(e.target.files[0])}/></label><div className="media-grid">{images.map(img=><button key={img.url} onClick={()=>chooseImage(img.url)}><img src={img.url} alt={img.name}/><small>{img.name}</small></button>)}</div></section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<Admin/>);
